-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "chiroptera"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#b4b4ce" })
hi(0, "@boolean", { fg = "#d2a374" })
hi(0, "@character", { fg = "#deb896", italic = true })
hi(0, "@character.special", { fg = "#7894ab" })
hi(0, "@constant", { fg = "#b4b4ce" })
hi(0, "@constant.builtin", { fg = "#d2a374" })
hi(0, "@constant.macro", { fg = "#b4b4ce" })
hi(0, "@constructor", { fg = "#b4b4ce" })
hi(0, "@constructor.lua", { fg = "#a1b3b9" })
hi(0, "@diff.delta", { fg = "#e6be8c" })
hi(0, "@diff.minus", { fg = "#d2788c" })
hi(0, "@diff.plus", { fg = "#8faf77" })
hi(0, "@function", { fg = "#be8c8c" })
hi(0, "@function.builtin", { fg = "#be8c8c" })
hi(0, "@function.call", { fg = "#b9a3ba" })
hi(0, "@function.macro", { fg = "#b4b4ce" })
hi(0, "@function.method", { fg = "#be8c8c" })
hi(0, "@function.method.call", { fg = "#a1b3b9" })
hi(0, "@keyword", { fg = "#7894ab" })
hi(0, "@keyword.conditional", { fg = "#7894ab" })
hi(0, "@keyword.exception", { fg = "#7894ab" })
hi(0, "@keyword.import", { fg = "#b4b4ce" })
hi(0, "@keyword.operator", { fg = "#7894ab" })
hi(0, "@keyword.return", { fg = "#7894ab" })
hi(0, "@label", { fg = "#7894ab" })
hi(0, "@lsp.type.builtinConstant", { fg = "#d2a374" })
hi(0, "@lsp.type.builtinType", { fg = "#bad1ce" })
hi(0, "@lsp.type.class", { fg = "#b4b4ce" })
hi(0, "@lsp.type.comment", { fg = "#646477", italic = true })
hi(0, "@lsp.type.decorator", { link = "Function" })
hi(0, "@lsp.type.enum", { fg = "#b4b4ce" })
hi(0, "@lsp.type.enumMember", { fg = "#bad1ce" })
hi(0, "@lsp.type.function", { fg = "#b9a3ba" })
hi(0, "@lsp.type.generic", { fg = "#a1b3b9" })
hi(0, "@lsp.type.interface", { fg = "#b4b4ce" })
hi(0, "@lsp.type.macro", { fg = "#b4b4ce" })
hi(0, "@lsp.type.method", { fg = "#be8c8c" })
hi(0, "@lsp.type.namespace", { fg = "#b4b4ce" })
hi(0, "@lsp.type.parameter", { fg = "#b9a3ba" })
hi(0, "@lsp.type.property", { fg = "#a1b3b9" })
hi(0, "@lsp.type.selfParameter", { fg = "#bad1ce" })
hi(0, "@lsp.type.struct", { link = "Structure" })
hi(0, "@lsp.type.type", { link = "Type" })
hi(0, "@lsp.type.typeParameter", { fg = "#b4b4ce" })
hi(0, "@lsp.type.variable", { fg = "#b4b4ce" })
hi(0, "@lsp.typemod.function", { fg = "#b9a3ba" })
hi(0, "@lsp.typemod.function.builtin", { fg = "#be8c8c" })
hi(0, "@lsp.typemod.function.defaultLibrary", { fg = "#be8c8c" })
hi(0, "@lsp.typemod.function.definition", { fg = "#be8c8c" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { fg = "#d2a374" })
hi(0, "@lsp.typemod.variable.definition", { fg = "#c7c7d4" })
hi(0, "@markup", { fg = "#cdcdcd" })
hi(0, "@markup.heading", { bold = true, fg = "#7894ab" })
hi(0, "@markup.italic", { fg = "#cdcdcd", italic = true })
hi(0, "@markup.link", { fg = "#deb896" })
hi(0, "@markup.link.uri", { fg = "#deb896", underline = true })
hi(0, "@markup.list", { fg = "#be8c8c" })
hi(0, "@markup.list.checked", { fg = "#be8c8c" })
hi(0, "@markup.list.unchecked", { fg = "#be8c8c" })
hi(0, "@markup.math", { fg = "#deb896" })
hi(0, "@markup.quote.markdown", { fg = "#646477" })
hi(0, "@markup.raw", { fg = "#b4b4ce" })
hi(0, "@markup.strikethrough", { fg = "#646477", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#cdcdcd" })
hi(0, "@markup.underline", { fg = "#cdcdcd", underline = true })
hi(0, "@module", { fg = "#b4b4ce" })
hi(0, "@number", { fg = "#d2a374" })
hi(0, "@number.float", { fg = "#d2a374" })
hi(0, "@operator", { fg = "#96a3b2" })
hi(0, "@property", { fg = "#c7c7d4" })
hi(0, "@punctuation.bracket", { fg = "#cdcdcd" })
hi(0, "@punctuation.delimiter", { fg = "#cdcdcd" })
hi(0, "@punctuation.special", { fg = "#7894ab" })
hi(0, "@string", { fg = "#deb896", italic = true })
hi(0, "@string.documentation", { fg = "#646477", italic = true })
hi(0, "@string.escape", { fg = "#7894ab" })
hi(0, "@string.regexp", { fg = "#7894ab" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.symbol", { fg = "#b4b4ce" })
hi(0, "@string.special.url", { fg = "#be8c8c" })
hi(0, "@tag.attribute", { fg = "#b4b4ce" })
hi(0, "@tag.delimiter", { fg = "#cdcdcd" })
hi(0, "@text.literal", { link = "Comment" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@type", { fg = "#a1b3b9" })
hi(0, "@type.builtin", { fg = "#bad1ce" })
hi(0, "@type.declaration", { fg = "#b4b4ce" })
hi(0, "@type.definition", { fg = "#b4b4ce" })
hi(0, "@variable", { fg = "#cdcdcd" })
hi(0, "@variable.builtin", { fg = "#bad1ce" })
hi(0, "@variable.member", { fg = "#bad1ce" })
hi(0, "@variable.parameter", { fg = "#b9a3ba" })
hi(0, "Boolean", { fg = "#d2a374" })
hi(0, "Character", { fg = "#deb896" })
hi(0, "CmpItemAbbr", { fg = "#cdcdcd" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#646477", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { fg = "#7894ab" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#7894ab", underline = true })
hi(0, "CmpItemKind", { fg = "#646477" })
hi(0, "CmpItemKindFunction", { fg = "#be8c8c" })
hi(0, "CmpItemKindInterfaceDefault", { fg = "#a1b3b9" })
hi(0, "CmpItemMenu", { fg = "#646477" })
hi(0, "ColorColumn", { bg = "#282830", ctermbg = 1 })
hi(0, "Comment", { ctermfg = 14, fg = "#646477", italic = true })
hi(0, "Conceal", { bg = "#1b1f25", ctermbg = 242, ctermfg = 7, fg = "#be8c8c" })
hi(0, "Conditional", { fg = "#7894ab" })
hi(0, "Constant", { ctermfg = 13, fg = "#b4b4ce" })
hi(0, "CurSearch", { bg = "#465362", fg = "#cdcdcd" })
hi(0, "Cursor", { reverse = true })
hi(0, "CursorColumn", { bg = "#282830", ctermbg = 242 })
hi(0, "CursorIM", { reverse = true })
hi(0, "CursorLine", { bg = "#282830" })
hi(0, "CursorLineNr", { ctermfg = 11, fg = "#cdcdcd" })
hi(0, "DashboardCenter", { fg = "#cdcdcd" })
hi(0, "DashboardFooter", { fg = "#b9a3ba", italic = true })
hi(0, "DashboardHeader", { fg = "#7894ab" })
hi(0, "DashboardShortCut", { fg = "#b4b4ce" })
hi(0, "Debug", { fg = "#b4b4ce" })
hi(0, "Define", { fg = "#646477" })
hi(0, "Delimiter", { fg = "#cdcdcd" })
hi(0, "DiagnosticError", { bold = true, ctermfg = 1, fg = "#d2788c" })
hi(0, "DiagnosticHint", { ctermfg = 7, fg = "#8ca0dc" })
hi(0, "DiagnosticInfo", { ctermfg = 4, fg = "#e6be8c" })
hi(0, "DiagnosticUnderlineError", { sp = "#d2788c", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#8ca0dc", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#8ca0dc", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e6be8c", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bold = true, fg = "#d2788c" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#8ca0dc" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#8ca0dc" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#e6be8c" })
hi(0, "DiagnosticWarn", { ctermfg = 3, fg = "#e6be8c" })
hi(0, "DiffAdd", { ctermbg = 4, fg = "#8faf77" })
hi(0, "DiffChange", { ctermbg = 5, fg = "#e6be8c" })
hi(0, "DiffDelete", { ctermbg = 6, ctermfg = 12, fg = "#d2788c" })
hi(0, "DiffFile", { fg = "#7894ab" })
hi(0, "DiffIndexLine", { fg = "#646477" })
hi(0, "DiffText", { ctermbg = 9, fg = "#cdcdcd" })
hi(0, "Directory", { ctermfg = 159, fg = "#8ca0dc" })
hi(0, "EndOfBuffer", {})
hi(0, "Error", { ctermbg = 9, ctermfg = 15, fg = "#d2788c" })
hi(0, "ErrorMsg", { bold = true, ctermbg = 1, ctermfg = 15, fg = "#d2788c" })
hi(0, "Exception", { fg = "#7894ab" })
hi(0, "Float", { fg = "#d2a374" })
hi(0, "FloatBorder", { bg = "#1b1f25", fg = "#878787" })
hi(0, "FloatFooter", { bg = "#1b1f25", fg = "#878787" })
hi(0, "FloatTitle", { bg = "#1b1f25", fg = "#878787" })
hi(0, "FoldColumn", { bg = "#1b1f25", ctermbg = 242, ctermfg = 14, fg = "#646477" })
hi(0, "Folded", { bg = "#282830", ctermbg = 242, ctermfg = 14, fg = "#646477" })
hi(0, "Function", { fg = "#be8c8c" })
hi(0, "GitSignsAdd", { fg = "#8faf77" })
hi(0, "GitSignsAddLn", { fg = "#8faf77" })
hi(0, "GitSignsAddNr", { fg = "#8faf77" })
hi(0, "GitSignsChange", { fg = "#e6be8c" })
hi(0, "GitSignsChangeLn", { fg = "#e6be8c" })
hi(0, "GitSignsChangeNr", { fg = "#e6be8c" })
hi(0, "GitSignsDelete", { fg = "#d2788c" })
hi(0, "GitSignsDeleteLn", { fg = "#d2788c" })
hi(0, "GitSignsDeleteNr", { fg = "#d2788c" })
hi(0, "GitSignsStagedAdd", { fg = "#47573b" })
hi(0, "GitSignsStagedAddCul", { fg = "#47573b" })
hi(0, "GitSignsStagedAddLn", { fg = "#47573b" })
hi(0, "GitSignsStagedAddNr", { fg = "#47573b" })
hi(0, "GitSignsStagedChange", { fg = "#735f46" })
hi(0, "GitSignsStagedChangeCul", { fg = "#735f46" })
hi(0, "GitSignsStagedChangeLn", { fg = "#735f46" })
hi(0, "GitSignsStagedChangeNr", { fg = "#735f46" })
hi(0, "GitSignsStagedChangedelete", { fg = "#735f46" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#735f46" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#735f46" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#735f46" })
hi(0, "GitSignsStagedDelete", { fg = "#693c46" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#693c46" })
hi(0, "GitSignsStagedDeleteLn", { fg = "#693c46" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#693c46" })
hi(0, "GitSignsStagedTopdelete", { fg = "#693c46" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#693c46" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#693c46" })
hi(0, "Identifier", { ctermfg = 14, fg = "#b4b4ce" })
hi(0, "Ignore", { ctermfg = 0, fg = "#1b1f25" })
hi(0, "IncSearch", { bg = "#465362", fg = "#1b1f25" })
hi(0, "Include", { fg = "#7894ab" })
hi(0, "Keyword", { fg = "#7894ab" })
hi(0, "Label", { fg = "#7894ab" })
hi(0, "LineNr", { ctermfg = 11, fg = "#646477" })
hi(0, "LspCodeLens", { fg = "#646477", italic = true })
hi(0, "LspCodeLensSeparator", { fg = "#646477" })
hi(0, "LspCxxHlGroupEnumConstant", { fg = "#a1b3b9" })
hi(0, "LspCxxHlGroupMemberVariable", { fg = "#a1b3b9" })
hi(0, "LspCxxHlGroupNamespace", { fg = "#be8c8c" })
hi(0, "LspCxxHlSkippedRegion", { fg = "#646477" })
hi(0, "LspCxxHlSkippedRegionBeginEnd", { fg = "#96a3b2" })
hi(0, "LspReferenceRead", { bg = "#646477" })
hi(0, "LspReferenceText", { bg = "#646477" })
hi(0, "LspReferenceWrite", { bg = "#646477" })
hi(0, "Macro", { fg = "#b4b4ce" })
hi(0, "MatchParen", { bg = "#363738", ctermbg = 6, fg = "#cdcdcd" })
hi(0, "MiniStatuslineDevinfo", { bg = "#646477", fg = "#cdcdcd" })
hi(0, "MiniStatuslineFileinfo", { bg = "#646477", fg = "#cdcdcd" })
hi(0, "MiniStatuslineFilename", { bg = "#1b1f25", fg = "#646477" })
hi(0, "MiniStatuslineInactive", { bg = "#1b1f25", fg = "#646477" })
hi(0, "MiniStatuslineModeCommand", { ctermbg = 9, fg = "#cdcdcd" })
hi(0, "MiniStatuslineModeInsert", { ctermbg = 5, fg = "#e6be8c" })
hi(0, "MiniStatuslineModeNormal", { reverse = true })
hi(0, "MiniStatuslineModeOther", { bg = "#465362", fg = "#1b1f25" })
hi(0, "MiniStatuslineModeReplace", { ctermbg = 6, ctermfg = 12, fg = "#d2788c" })
hi(0, "MiniStatuslineModeVisual", { ctermbg = 4, fg = "#8faf77" })
hi(0, "MiniSurround", { bg = "#465362", fg = "#1b1f25" })
hi(0, "ModeMsg", { fg = "#deb896" })
hi(0, "MoreMsg", { bold = true, ctermfg = 121, fg = "#be8c8c" })
hi(0, "MsgSeparator", { bg = "#282830", bold = true, fg = "#deb896" })
hi(0, "NeoTreeEndOfBuffer", { bg = "#1b1f25", fg = "#646477" })
hi(0, "NeoTreeGitAdded", { fg = "#8faf77" })
hi(0, "NeoTreeGitConflict", { fg = "#d2788c" })
hi(0, "NeoTreeGitDeleted", { fg = "#d2788c" })
hi(0, "NeoTreeGitModified", { fg = "#e6be8c" })
hi(0, "NeoTreeGitUntracked", { fg = "#d2788c" })
hi(0, "NeoTreeIndentMarker", { fg = "#646477" })
hi(0, "NeoTreeNormal", { bg = "#1b1f25", fg = "#cdcdcd" })
hi(0, "NeoTreeNormalNC", { bg = "#1b1f25", fg = "#cdcdcd" })
hi(0, "NeoTreeRootName", { fg = "#8ca0dc" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#8ca0dc" })
hi(0, "NeoTreeVertSplit", { bg = "#646477", fg = "#646477" })
hi(0, "NeoTreeWinSeparator", { bg = "#646477", fg = "#646477" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#be8c8c" })
hi(0, "NeotestDir", { fg = "#646477" })
hi(0, "NeotestFailed", { fg = "#d2788c" })
hi(0, "NeotestFile", { fg = "#b4b4ce" })
hi(0, "NeotestFocused", { bold = true, fg = "#8ca0dc" })
hi(0, "NeotestIndent", { fg = "#646477" })
hi(0, "NeotestMarked", { fg = "#e6be8c" })
hi(0, "NeotestNamespace", { fg = "#b9a3ba" })
hi(0, "NeotestPassed", { fg = "#8faf77" })
hi(0, "NeotestRunning", { fg = "#8ca0dc" })
hi(0, "NeotestSkipped", { fg = "#e6be8c" })
hi(0, "NeotestTarget", { fg = "#be8c8c" })
hi(0, "NeotestTest", { fg = "#cdcdcd" })
hi(0, "NeotestUnknown", { fg = "#cdcdcd" })
hi(0, "NeotestWatching", { fg = "#e6be8c" })
hi(0, "NonText", { ctermfg = 12, fg = "#646477" })
hi(0, "Normal", { bg = "#1b1f25", fg = "#cdcdcd" }) --18191a
hi(0, "NormalFloat", { bg = "#1b1f25", fg = "#cdcdcd" })
hi(0, "Number", { fg = "#d2a374" })
hi(0, "Operator", { fg = "#96a3b2" })
hi(0, "Pmenu", { bg = "#363738", ctermbg = 13, ctermfg = 0, fg = "#cdcdcd" })
hi(0, "PmenuSbar", { bg = "#363738", ctermbg = 248 })
hi(0, "PmenuSel", { bg = "#1b1f25", ctermbg = 0, ctermfg = 242 })
hi(0, "PmenuThumb", { bg = "#363738", ctermbg = 15 })
hi(0, "PreCondit", { fg = "#646477" })
hi(0, "PreProc", { ctermfg = 81, fg = "#b4b4ce" })
hi(0, "Question", { ctermfg = 121, fg = "#b4b4ce" })
hi(0, "QuickFixLine", { fg = "#be8c8c", underline = true })
hi(0, "Repeat", { fg = "#7894ab" })
hi(0, "Search", { bg = "#465362", ctermbg = 11, ctermfg = 0, fg = "#cdcdcd" })
hi(0, "SignColumn", { bg = "#1b1f25", ctermbg = 242, ctermfg = 14, fg = "#cdcdcd" })
hi(0, "Special", { ctermfg = 224, fg = "#bad1ce" })
hi(0, "SpecialChar", { fg = "#7894ab" })
hi(0, "SpecialComment", { fg = "#7894ab" })
hi(0, "SpecialKey", { ctermfg = 81, fg = "#646477" })
hi(0, "SpellBad", { ctermbg = 9, undercurl = true })
hi(0, "SpellCap", { ctermbg = 12, undercurl = true })
hi(0, "SpellLocal", { ctermbg = 14, undercurl = true })
hi(0, "SpellRare", { ctermbg = 13, undercurl = true })
hi(0, "Statement", { ctermfg = 11, fg = "#7894ab" })
hi(0, "StatusLine", { bg = "#646477", fg = "#cdcdcd" })
hi(0, "StatusLineNC", { bg = "#1b1f25", fg = "#646477" })
hi(0, "StatusLineTerm", { bg = "#282830", fg = "#cdcdcd" })
hi(0, "StatusLineTermNC", { bg = "#282830", fg = "#646477" })
hi(0, "StorageClass", { fg = "#b4b4ce" })
hi(0, "String", { fg = "#deb896", italic = true })
hi(0, "Structure", { fg = "#b4b4ce" })
hi(0, "Substitute", { bg = "#363738", fg = "#a1b3b9" })
hi(0, "TabLine", { bg = "#282830", ctermbg = 242, ctermfg = 15, fg = "#cdcdcd" })
hi(0, "TabLineFill", { bg = "#282830", fg = "#646477" })
hi(0, "TabLineSel", { bg = "#cdcdcd", fg = "#1b1f25" })
hi(0, "Tag", { fg = "#bad1ce" })
hi(0, "TelescopeBorder", { fg = "#878787" })
hi(0, "TelescopeMatching", { bold = true, fg = "#e6be8c" })
hi(0, "TelescopePromptPrefix", { fg = "#b4b4ce" })
hi(0, "TelescopeResultsNormal", { fg = "#cdcdcd" })
hi(0, "TelescopeSelection", { bg = "#282830", fg = "#b4b4ce" })
hi(0, "TelescopeSelectionCaret", { fg = "#a1b3b9" })
hi(0, "Terminal", { bg = "#1b1f25", fg = "#cdcdcd" })
hi(0, "Title", { ctermfg = 225, fg = "#c7c7d4" })
hi(0, "Todo", { ctermbg = 11, ctermfg = 0, fg = "#be8c8c", italic = true })
hi(0, "ToolbarButton", { bg = "#363738", fg = "#1b1f25" })
hi(0, "ToolbarLine", { fg = "#cdcdcd" })
hi(0, "Type", { ctermfg = 121, fg = "#a1b3b9" })
hi(0, "Typedef", { fg = "#b4b4ce" })
hi(0, "Visual", { bg = "#363738", ctermbg = 242, fg = "#cdcdcd" })
hi(0, "VisualNOS", { bg = "#646477", underline = true })
hi(0, "WarningMsg", { bold = true, ctermfg = 224, fg = "#e6be8c" })
hi(0, "Whitespace", { fg = "#646477" })
hi(0, "WildMenu", { bg = "#be8c8c", ctermbg = 11, ctermfg = 0, fg = "#1b1f25" })
hi(0, "WinSeparator", {})
hi(0, "debugBreakpoint", { bg = "#96a3b2", fg = "#1b1f25" })
hi(0, "debugPC", { bg = "#cdcdcd", fg = "#1b1f25" })
hi(0, "diffAdded", { fg = "#8faf77" })
hi(0, "diffRemoved", { fg = "#d2788c" })
hi(0, "iCursor", { reverse = true })
hi(0, "lCursor", { reverse = true })
hi(0, "vCursor", { reverse = true })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1b1f25"
g.terminal_color_1 = "#d2788c"
g.terminal_color_2 = "#8faf77"
g.terminal_color_3 = "#e6be8c"
g.terminal_color_4 = "#8ca0dc"
g.terminal_color_5 = "#c7c7d4"
g.terminal_color_6 = "#a1b3b9"
g.terminal_color_7 = "#cdcdcd"
g.terminal_color_8 = "#878787"
g.terminal_color_9 = "#d2788c"
g.terminal_color_10 = "#8faf77"
g.terminal_color_11 = "#e6be8c"
g.terminal_color_12 = "#8ca0dc"
g.terminal_color_13 = "#c7c7d4"
g.terminal_color_14 = "#a1b3b9"
g.terminal_color_15 = "#cdcdcd"
