-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

-- if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
-- vim.g.colors_name = "vespertine"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@attribute.diff", { fg = "#44EAB0" })
hi(0, "@character.special", { link = "Character" })
hi(0, "@class", { fg = "#fff3ca" })
hi(0, "@comment.error", { fg = "#fbadff" })
hi(0, "@comment.hint", { bg = "#2d3948", blend = 20, fg = "#729fcf" })
hi(0, "@comment.info", { bg = "#494a47", blend = 20, fg = "#fff3ca" })
hi(0, "@comment.note", { bg = "#493e36", blend = 20, fg = "#729fcf" })--ffb578"
hi(0, "@comment.todo", { bg = "#164d44", blend = 20, fg = "#44EAB0" })
hi(0, "@comment.warning", { fg = "#44EAB0" })
hi(0, "@conceal", { link = "Conceal" })
hi(0, "@conceal.markdown", { fg = "#9a9184" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant", { fg = "#44EAB0" })
hi(0, "@constant.builtin", { bold = true, fg = "#ABB4E3" })
hi(0, "@constant.macro", { fg = "#44EAB0" })
hi(0, "@constructor", { fg = "#fff3ca" })
hi(0, "@diff.delta", { bg = "#164d44", blend = 20 })
hi(0, "@diff.minus", { bg = "#493c51", blend = 20, fg = "#fbadff" })
hi(0, "@diff.plus", { bg = "#494a47", blend = 20, fg = "#fff3ca" })
hi(0, "@field", { fg = "#fff3ca" })
hi(0, "@float", { link = "Number" })
hi(0, "@function", { fg = "#fff3ca" }) --12ECA1
hi(0, "@function.builtin", { fg = "#ABB4E3" }) --67574c
hi(0, "@function.macro", { link = "Function" })
hi(0, "@function.method", { fg = "#44EAB0" })
hi(0, "@function.method.call", { fg = "#ABB4E3" }) --67547c
hi(0, "@include", { link = "Include" })
hi(0, "@interface", { fg = "#fff3ca" })
hi(0, "@keyword.function.python", { fg = "#ABB4E3" })--ffb578"
hi(0, "@keyword.conditional", { fg = "#729fcf" })--ffb578"
hi(0, "@keyword.conditional.ternary", { fg = "#729fcf" })--ffb578"
hi(0, "@keyword.debug", { fg = "#44EAB0" })
hi(0, "@keyword.directive", { fg = "#729fcf" })
hi(0, "@keyword.directive.define", { fg = "#729fcf" })
hi(0, "@keyword.exception", { fg = "#729fcf" })--ffb578"
hi(0, "@keyword.import", { fg = "#729fcf" })--ffb578"
hi(0, "@keyword.operator", { fg = "#fff3ca" }) --959da7
hi(0, "@keyword.repeat", { fg = "#729fcf" })--ffb578"
hi(0, "@keyword.return", { fg = "#729fcf" })--ffb578"
hi(0, "@keyword.storage", { fg = "#fff3ca" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.type.variable.svelte", { link = "@variable" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.constant", { link = "@constant" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "@type" })
hi(0, "@markup.heading", { bold = true, fg = "#fff3ca" })
hi(0, "@markup.heading.1.markdown", { link = "markdownH1" })
hi(0, "@markup.heading.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@markup.heading.2.markdown", { link = "markdownH2" })
hi(0, "@markup.heading.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@markup.heading.3.markdown", { link = "markdownH3" })
hi(0, "@markup.heading.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@markup.heading.4.markdown", { link = "markdownH4" })
hi(0, "@markup.heading.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@markup.heading.5.markdown", { link = "markdownH5" })
hi(0, "@markup.heading.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@markup.heading.6.markdown", { link = "markdownH6" })
hi(0, "@markup.heading.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@markup.link.label.markdown_inline", { fg = "#fff3ca" })
hi(0, "@markup.link.markdown_inline", { fg = "#9a9184" })
hi(0, "@markup.link.url", { fg = "#729fcf" })
hi(0, "@markup.list", { fg = "#ABB4E3" })
hi(0, "@markup.list.checked", { bg = "#333536", blend = 10, fg = "#fff3ca" })
hi(0, "@markup.list.unchecked", { fg = "#ABB4E3" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.quote", { fg = "#9a9184" })
hi(0, "@markup.raw.delimiter.markdown", { fg = "#9a9184" })
hi(0, "@markup.raw.markdown_inline", { fg = "#44EAB0" })
hi(0, "@method", { fg = "#44EAB0" })
hi(0, "@module", { fg = "#ABB4E3" })
hi(0, "@module.builtin", { bold = true, fg = "#ABB4E3" })
hi(0, "@namespace", { link = "Include" })
hi(0, "@number.float", { link = "Number" })
hi(0, "@parameter", { fg = "#729fcf", italic = true })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#fff3ca", italic = true })
hi(0, "@punctuation", { fg = "#9a9184" })
hi(0, "@punctuation.bracket", { fg = "#9a9184" })
hi(0, "@punctuation.delimiter", { fg = "#9a9184" })
hi(0, "@punctuation.special", { fg = "#9a9184" })
hi(0, "@regexp", { link = "String" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.escape", { fg = "#729fcf" })--ffb578
hi(0, "@string.regexp", { fg = "#729fcf" })
hi(0, "@string.special", { link = "String" })
hi(0, "@string.special.symbol", { link = "Identifier" })
hi(0, "@string.special.url", { fg = "#729fcf" })
hi(0, "@symbol", { link = "Identifier" })
hi(0, "@tag.attribute", { fg = "#729fcf" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#9a9184" })
hi(0, "@text", { fg = "#ABB4E3" })
hi(0, "@text.danger", { fg = "#fbadff" })
hi(0, "@text.diff.add", { bg = "#494a47", blend = 20, fg = "#fff3ca" })
hi(0, "@text.diff.delete", { bg = "#493c51", blend = 20, fg = "#fbadff" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.math", { link = "Special" })
hi(0, "@text.note", { link = "SpecialComment" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.title.1.markdown", { link = "markdownH1" })
hi(0, "@text.title.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@text.title.2.markdown", { link = "markdownH2" })
hi(0, "@text.title.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@text.title.3.markdown", { link = "markdownH3" })
hi(0, "@text.title.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@text.title.4.markdown", { link = "markdownH4" })
hi(0, "@text.title.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@text.title.5.markdown", { link = "markdownH5" })
hi(0, "@text.title.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@text.title.6.markdown", { link = "markdownH6" })
hi(0, "@text.title.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#729fcf" })
hi(0, "@text.warning", { fg = "#44EAB0" })
hi(0, "@todo", { link = "Todo" })
hi(0, "@type", { fg = "#fff3ca" })
hi(0, "@type.builtin", { bold = true, fg = "#fff3ca" })
hi(0, "@variable", { fg = "#ABB4E3", italic = true })
hi(0, "@variable.builtin", { bold = true, fg = "#fbadff" })
hi(0, "@variable.member", { fg = "#fff3ca" })
hi(0, "@variable.parameter", { fg = "#729fcf", italic = true })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "AlphaButtons", { fg = "#fff3ca" })
hi(0, "AlphaFooter", { fg = "#44EAB0" })
hi(0, "AlphaHeader", { fg = "#729fcf" })--ffb578"
hi(0, "AlphaShortcut", { fg = "#44EAB0" })
hi(0, "Boolean", { fg = "#44EAB0" })
hi(0, "BufferCurrent", { bg = "#272f3a", fg = "#ABB4E3" })
hi(0, "BufferCurrentIndex", { bg = "#272f3a", fg = "#ABB4E3" })
hi(0, "BufferCurrentMod", { bg = "#272f3a", fg = "#fff3ca" })
hi(0, "BufferCurrentSign", { bg = "#272f3a", fg = "#9a9184" })
hi(0, "BufferCurrentTarget", { bg = "#272f3a", fg = "#44EAB0" })
hi(0, "BufferInactive", { fg = "#9a9184" })
hi(0, "BufferInactiveIndex", { fg = "#9a9184" })
hi(0, "BufferInactiveMod", { fg = "#fff3ca" })
hi(0, "BufferInactiveSign", { fg = "#737982" })
hi(0, "BufferInactiveTarget", { fg = "#44EAB0" })
hi(0, "BufferVisible", { fg = "#9a9184" })
hi(0, "BufferVisibleIndex", { fg = "#9a9184" })
hi(0, "BufferVisibleMod", { fg = "#fff3ca" })
hi(0, "BufferVisibleSign", { fg = "#737982" })
hi(0, "BufferVisibleTarget", { fg = "#44EAB0" })
hi(0, "Character", { fg = "#44EAB0" })
hi(0, "CmpItemAbbr", { fg = "#9a9184" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#9a9184", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#ABB4E3" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#ABB4E3" })
hi(0, "CmpItemKind", { fg = "#9a9184" })
hi(0, "CmpItemKindClass", { link = "StorageClass" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindMethod", { link = "PreProc" })
hi(0, "CmpItemKindSnippet", { link = "String" })
hi(0, "CmpItemKindVariable", { link = "Identifier" })
hi(0, "ColorColumn", { bg = "#222830" })
hi(0, "Comment", { fg = "#494a47", italic = true })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#729fcf" })--ffb578"
hi(0, "Constant", { fg = "#44EAB0" })
hi(0, "CopilotSuggestion", { fg = "#737982", italic = true })
hi(0, "CurSearch", { bg = "#44EAB0", fg = "#1c2026" })
hi(0, "Cursor", { bg = "#ABB4E3", fg = "#616770" })
hi(0, "CursorColumn", { bg = "#272f3a" })
hi(0, "CursorLine", { bg = "#272f3a" })
hi(0, "CursorLineNr", { fg = "#ABB4E3", bg = "#272f3a" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#44EAB0" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#737982" })
hi(0, "DapUIBreakpointsInfo", { link = "DapUIThread" })
hi(0, "DapUIBreakpointsLine", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIBreakpointsPath", { fg = "#fff3ca" })
hi(0, "DapUIDecoration", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIFloatBorder", { fg = "#737982" })
hi(0, "DapUIFrameName", { fg = "#ABB4E3" })
hi(0, "DapUILineNumber", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#fff3ca" })
hi(0, "DapUIScope", { link = "DapUIBreakpointsPath" })
hi(0, "DapUISource", { fg = "#729fcf" })
hi(0, "DapUIStoppedThread", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIThread", { fg = "#44EAB0" })
hi(0, "DapUIValue", { fg = "#ABB4E3" })
hi(0, "DapUIVariable", { fg = "#ABB4E3" })
hi(0, "DapUIWatchesEmpty", { fg = "#fbadff" })
hi(0, "DapUIWatchesError", { link = "DapUIWatchesEmpty" })
hi(0, "DapUIWatchesValue", { link = "DapUIThread" })
hi(0, "DashboardCenter", { fg = "#44EAB0" })
hi(0, "DashboardFooter", { fg = "#729fcf" })
hi(0, "DashboardHeader", { fg = "#729fcf" })--ffb578"
hi(0, "DashboardShortcut", { fg = "#fbadff" })
hi(0, "Debug", { fg = "#44EAB0" })
hi(0, "Define", { fg = "#729fcf" })
hi(0, "DefinitionCount", { fg = "#44EAB0" })
hi(0, "DefinitionIcon", { fg = "#44EAB0" })
hi(0, "DefinitionPreviewTitle", { bold = true, fg = "#44EAB0" })
hi(0, "Delimiter", { fg = "#9a9184" })
hi(0, "DiagnosticDefaultError", { link = "DiagnosticError" })
hi(0, "DiagnosticDefaultHint", { link = "DiagnosticHint" })
hi(0, "DiagnosticDefaultInfo", { link = "DiagnosticInfo" })
hi(0, "DiagnosticDefaultWarn", { link = "DiagnosticWarn" })
hi(0, "DiagnosticError", { fg = "#fbadff" })
hi(0, "DiagnosticHint", { fg = "#729fcf" })
hi(0, "DiagnosticInfo", { fg = "#fff3ca" })
hi(0, "DiagnosticUnderlineError", { sp = "#fbadff", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#729fcf", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#fff3ca", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#44EAB0", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#fbadff" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#729fcf" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#fff3ca" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#44EAB0" })
hi(0, "DiagnosticWarn", { fg = "#44EAB0" })
hi(0, "DiffAdd", { bg = "#494a47", blend = 20 })
hi(0, "DiffChange", { bg = "#164d44", blend = 20 })
hi(0, "DiffDelete", { bg = "#493c51", blend = 20 })
hi(0, "DiffText", { bg = "#164d44", blend = 20 })
hi(0, "Directory", { bold = true, fg = "#fff3ca" })
hi(0, "Error", { fg = "#fbadff" })
hi(0, "ErrorMsg", { bold = true, fg = "#fbadff" })
hi(0, "Exception", { fg = "#729fcf" })--ffb578"
hi(0, "FlashLabel", { bg = "#fbadff", fg = "#1c2026" })
hi(0, "Float", { fg = "#44EAB0" })
hi(0, "FloatBorder", { fg = "#737982" })
hi(0, "FloatTitle", { link = "Directory" })
hi(0, "FoldColumn", { fg = "#737982" })
hi(0, "Folded", { fg = "#ABB4E3" })
hi(0, "Function", { fg = "#44EAB0" })
hi(0, "FzfLuaBorder", { fg = "#737982" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#9a9184" })
hi(0, "FzfLuaBufFlagCur", { fg = "#9a9184" })
hi(0, "FzfLuaHeaderBind", { fg = "#44EAB0" })
hi(0, "FzfLuaHeaderText", { fg = "#fbadff" })
hi(0, "FzfLuaNormal", { link = "NormalFloat" })
hi(0, "FzfLuaTitle", { bold = true, fg = "#fff3ca" })
hi(0, "GitSignsAdd", { link = "SignAdd" })
hi(0, "GitSignsChange", { link = "SignChange" })
hi(0, "GitSignsDelete", { link = "SignDelete" })
hi(0, "HopNextKey", { bg = "#493c51", blend = 20, fg = "#fbadff" })
hi(0, "HopNextKey1", { bg = "#494a47", blend = 20, fg = "#fff3ca" })
hi(0, "HopNextKey2", { bg = "#493e36", blend = 20, fg = "#729fcf" })--ffb578"
hi(0, "HopUnmatched", { fg = "#737982" })
hi(0, "IblIndent", { fg = "#272f3a" })
hi(0, "IblScope", { fg = "#fff3ca" })
hi(0, "IblWhitespace", { fg = "#272f3a" })
hi(0, "Identifier", { fg = "#ABB4E3" })
hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
hi(0, "Include", { fg = "#729fcf" })--ffb578"
hi(0, "IndentBlanklineChar", { fg = "#737982", nocombine = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#737982", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#737982", nocombine = true })
hi(0, "Keyword", { fg = "#729fcf" })--ffb578"
hi(0, "Label", { fg = "#fff3ca" })
hi(0, "LeapLabelPrimary", { link = "IncSearch" })
hi(0, "LeapLabelSecondary", { link = "StatusLineTerm" })
hi(0, "LeapMatch", { link = "MatchParen" })
hi(0, "LineNr", { fg = "#737982" })
hi(0, "LspCodeLens", { fg = "#9a9184" })
hi(0, "LspCodeLensSeparator", { fg = "#737982" })
hi(0, "LspFloatWinBorder", { fg = "#737982" })
hi(0, "LspFloatWinNormal", { bg = "#222830" })
hi(0, "LspInlayHint", { bg = "#25292f", blend = 10, fg = "#737982" })
hi(0, "LspReferenceRead", { bg = "#4d535c" })
hi(0, "LspReferenceText", { bg = "#4d535c" })
hi(0, "LspReferenceWrite", { bg = "#4d535c" })
hi(0, "LspSagaAutoPreview", { fg = "#9a9184" })
hi(0, "LspSagaCodeActionBorder", { fg = "#44EAB0" })
hi(0, "LspSagaCodeActionContent", { fg = "#fff3ca" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#44EAB0" })
hi(0, "LspSagaCodeActionTruncateLine", { link = "LspSagaCodeActionBorder" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#737982" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#44EAB0" })
hi(0, "LspSagaDiagnosticHeader", { bold = true, fg = "#fff3ca" })
hi(0, "LspSagaDiagnosticTruncateLine", { link = "LspSagaDiagnosticBorder" })
hi(0, "LspSagaDocTruncateLine", { link = "LspSagaHoverBorder" })
hi(0, "LspSagaFinderSelection", { fg = "#44EAB0" })
hi(0, "LspSagaHoverBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaLspFinderBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaRenameBorder", { fg = "#729fcf" })--ffb578"
hi(0, "LspSagaRenamePromptPrefix", { fg = "#fbadff" })
hi(0, "LspSagaShTruncateLine", { link = "LspSagaSignatureHelpBorder" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#fff3ca" })
hi(0, "LspSignatureActiveParameter", { bg = "#272f3a" })
hi(0, "Macro", { fg = "#729fcf" })
hi(0, "MatchParen", { bg = "#55453b", blend = 25, fg = "#729fcf" })--ffb578"
hi(0, "MiniClueTitle", { bold = true })
hi(0, "MiniDiffOverAdd", { bg = "#494a47", blend = 20, fg = "#fff3ca" })
hi(0, "MiniDiffOverChange", { bg = "#164d44", blend = 20, fg = "#44EAB0" })
hi(0, "MiniDiffOverContext", { bg = "#222830" })
hi(0, "MiniDiffOverDelete", { bg = "#493c51", blend = 20, fg = "#fbadff" })
hi(0, "MiniDiffSignAdd", { fg = "#fff3ca" })
hi(0, "MiniDiffSignChange", { fg = "#44EAB0" })
hi(0, "MiniDiffSignDelete", { fg = "#fbadff" })
hi(0, "MiniIndentscopeSymbol", { fg = "#737982" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#737982" })
hi(0, "MiniPickPrompt", { bold = true })
hi(0, "MiniStatuslineDevinfo", { bg = "#272f3a", fg = "#9a9184" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#222830", fg = "#737982" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#fbadff", bold = true, fg = "#1c2026" })
hi(0, "MiniStatuslineModeInsert", { bg = "#fff3ca", bold = true, fg = "#1c2026" })
hi(0, "MiniStatuslineModeNormal", { bg = "#44EAB0", bold = true, fg = "#1c2026" })
hi(0, "MiniStatuslineModeOther", { bg = "#44EAB0", bold = true, fg = "#1c2026" })
hi(0, "MiniStatuslineModeReplace", { bg = "#729fcf", bold = true, fg = "#1c2026" })--ffb578"
hi(0, "MiniStatuslineModeVisual", { bg = "#729fcf", bold = true, fg = "#1c2026" })
hi(0, "ModeMsg", { fg = "#9a9184" })
hi(0, "ModesCopy", { bg = "#44EAB0" })
hi(0, "ModesDelete", { bg = "#fbadff" })
hi(0, "ModesInsert", { bg = "#fff3ca" })
hi(0, "ModesVisual", { bg = "#729fcf" })
hi(0, "MoreMsg", { fg = "#729fcf" })
hi(0, "NavicIconsArray", { fg = "#44EAB0" })
hi(0, "NavicIconsBoolean", { fg = "#44EAB0" })
hi(0, "NavicIconsClass", { fg = "#fff3ca" })
hi(0, "NavicIconsConstant", { fg = "#44EAB0" })
hi(0, "NavicIconsConstructor", { fg = "#44EAB0" })
hi(0, "NavicIconsEnum", { fg = "#44EAB0" })
hi(0, "NavicIconsEnumMember", { fg = "#fff3ca" })
hi(0, "NavicIconsEvent", { fg = "#44EAB0" })
hi(0, "NavicIconsField", { fg = "#fff3ca" })
hi(0, "NavicIconsFile", { fg = "#737982" })
hi(0, "NavicIconsFunction", { fg = "#729fcf" })--ffb578"
hi(0, "NavicIconsInterface", { fg = "#fff3ca" })
hi(0, "NavicIconsKey", { fg = "#729fcf" })
hi(0, "NavicIconsKeyword", { fg = "#729fcf" })--ffb578"
hi(0, "NavicIconsMethod", { fg = "#729fcf" })
hi(0, "NavicIconsModule", { fg = "#44EAB0" })
hi(0, "NavicIconsNamespace", { fg = "#737982" })
hi(0, "NavicIconsNull", { fg = "#fbadff" })
hi(0, "NavicIconsNumber", { fg = "#44EAB0" })
hi(0, "NavicIconsObject", { fg = "#44EAB0" })
hi(0, "NavicIconsOperator", { fg = "#9a9184" })
hi(0, "NavicIconsPackage", { fg = "#737982" })
hi(0, "NavicIconsProperty", { fg = "#fff3ca" })
hi(0, "NavicIconsString", { fg = "#44EAB0" })
hi(0, "NavicIconsStruct", { fg = "#fff3ca" })
hi(0, "NavicIconsTypeParameter", { fg = "#fff3ca" })
hi(0, "NavicIconsVariable", { fg = "#ABB4E3" })
hi(0, "NavicSeparator", { fg = "#9a9184" })
hi(0, "NavicText", { fg = "#9a9184" })
hi(0, "NeoTreeGitAdded", { fg = "#fff3ca" })
hi(0, "NeoTreeGitConflict", { fg = "#729fcf" })
hi(0, "NeoTreeGitDeleted", { fg = "#fbadff" })
hi(0, "NeoTreeGitIgnored", { fg = "#737982" })
hi(0, "NeoTreeGitModified", { fg = "#44EAB0" })
hi(0, "NeoTreeGitRenamed", { fg = "#729fcf" })--ffb578"
hi(0, "NeoTreeGitUntracked", { fg = "#9a9184" })
hi(0, "NeoTreeTitleBar", { link = "StatusLineTerm" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#fff3ca", italic = true })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#44EAB0", italic = true })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#9a9184", italic = true })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#fbadff", italic = true })
hi(0, "NeogitChangeModified", { bold = true, fg = "#44EAB0", italic = true })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#729fcf", italic = true })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#729fcf", italic = true })--ffb578"
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#44EAB0", italic = true })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffContextHighlight", { bg = "#222830" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFilePath", { fg = "#fff3ca", italic = true })
hi(0, "NeogitHunkHeader", { bg = "#222830" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#222830" })
hi(0, "NeorgHeading1Prefix", { link = "markdownH1Delimiter" })
hi(0, "NeorgHeading1Title", { link = "markdownH1" })
hi(0, "NeorgHeading2Prefix", { link = "markdownH2Delimiter" })
hi(0, "NeorgHeading2Title", { link = "markdownH2" })
hi(0, "NeorgHeading3Prefix", { link = "markdownH3Delimiter" })
hi(0, "NeorgHeading3Title", { link = "markdownH3" })
hi(0, "NeorgHeading4Prefix", { link = "markdownH4Delimiter" })
hi(0, "NeorgHeading4Title", { link = "markdownH4" })
hi(0, "NeorgHeading5Prefix", { link = "markdownH5Delimiter" })
hi(0, "NeorgHeading5Title", { link = "markdownH5" })
hi(0, "NeorgHeading6Prefix", { link = "markdownH6Delimiter" })
hi(0, "NeorgHeading6Title", { link = "markdownH6" })
hi(0, "NeorgMarkerTitle", { bold = true, fg = "#fff3ca" })
hi(0, "NeotestAdapterName", { fg = "#729fcf" })
hi(0, "NeotestBorder", { fg = "#4d535c" })
hi(0, "NeotestDir", { fg = "#fff3ca" })
hi(0, "NeotestExpandMarker", { fg = "#4d535c" })
hi(0, "NeotestFailed", { fg = "#fbadff" })
hi(0, "NeotestFile", { fg = "#ABB4E3" })
hi(0, "NeotestFocused", { bg = "#4d535c", fg = "#44EAB0" })
hi(0, "NeotestMarked", { bold = true, fg = "#44EAB0" })
hi(0, "NeotestNamespace", { fg = "#44EAB0" })
hi(0, "NeotestPassed", { fg = "#729fcf" })--ffb578"
hi(0, "NeotestRunning", { fg = "#44EAB0" })
hi(0, "NeotestSkipped", { fg = "#9a9184" })
hi(0, "NeotestTarget", { fg = "#fbadff" })
hi(0, "NeotestTest", { fg = "#44EAB0" })
hi(0, "NeotestUnknown", { fg = "#9a9184" })
hi(0, "NeotestWatching", { fg = "#729fcf" })
hi(0, "NeotestWinSelect", { fg = "#737982" })
hi(0, "NoiceCursor", { bg = "#ABB4E3", fg = "#616770" })
hi(0, "NonText", { fg = "#737982" })
hi(0, "Normal", { fg = "#ABB4E3" })
hi(0, "NormalFloat", {})
hi(0, "NormalNC", { fg = "#ABB4E3" })
hi(0, "NotifyDEBUGBorder", { fg = "#737982" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGTitle", { fg = "#737982" })
hi(0, "NotifyERRORBorder", { fg = "#fbadff" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle", { fg = "#fbadff" })
hi(0, "NotifyINFOBorder", { fg = "#fff3ca" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOTitle", { fg = "#fff3ca" })
hi(0, "NotifyTRACEBorder", { fg = "#729fcf" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACETitle", { fg = "#729fcf" })
hi(0, "NotifyWARNBorder", { fg = "#44EAB0" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNTitle", { fg = "#44EAB0" })
hi(0, "Number", { fg = "#fff3ca" })
hi(0, "NvimInternalError", { link = "ErrorMsg" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#737982" })
hi(0, "NvimTreeFileDeleted", { fg = "#fbadff" })
hi(0, "NvimTreeFileDirty", { fg = "#44EAB0" })
hi(0, "NvimTreeFileMerge", { fg = "#729fcf" })
hi(0, "NvimTreeFileNew", { fg = "#fff3ca" })
hi(0, "NvimTreeFileRenamed", { fg = "#729fcf" })--ffb578"
hi(0, "NvimTreeFileStaged", { fg = "#729fcf" })
hi(0, "NvimTreeFolderIcon", { fg = "#9a9184" })
hi(0, "NvimTreeFolderName", { fg = "#fff3ca" })
hi(0, "NvimTreeGitDeleted", { fg = "#fbadff" })
hi(0, "NvimTreeGitDirty", { fg = "#44EAB0" })
hi(0, "NvimTreeGitIgnored", { fg = "#737982" })
hi(0, "NvimTreeGitMerge", { fg = "#729fcf" })
hi(0, "NvimTreeGitNew", { fg = "#fff3ca" })
hi(0, "NvimTreeGitRenamed", { fg = "#729fcf" })--ffb578"
hi(0, "NvimTreeGitStaged", { fg = "#729fcf" })
hi(0, "NvimTreeImageFile", { fg = "#ABB4E3" })
hi(0, "NvimTreeNormal", { link = "Normal" })
hi(0, "NvimTreeOpenedFile", { bg = "#272f3a", fg = "#ABB4E3" })
hi(0, "NvimTreeOpenedFolderName", { link = "NvimTreeFolderName" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#fff3ca" })
hi(0, "NvimTreeSpecialFile", { link = "NvimTreeNormal" })
hi(0, "NvimTreeWindowPicker", { link = "StatusLineTerm" })
hi(0, "Operator", { fg = "#9a9184" })
hi(0, "Pmenu", { fg = "#9a9184" })
hi(0, "PmenuExtra", { bg = "#222830", fg = "#737982" })
hi(0, "PmenuExtraSel", { bg = "#272f3a", fg = "#9a9184" })
hi(0, "PmenuKind", { fg = "#fff3ca" })
hi(0, "PmenuKindSel", { bg = "#272f3a", fg = "#9a9184" })
hi(0, "PmenuSbar", { bg = "#222830" })
hi(0, "PmenuSel", { bg = "#272f3a", fg = "#ABB4E3" })
hi(0, "PmenuThumb", { bg = "#737982" })
hi(0, "PounceAccept", { bg = "#493c51", blend = 20, fg = "#fbadff" })
hi(0, "PounceAcceptBest", { bg = "#164d44", blend = 20, fg = "#44EAB0" })
hi(0, "PounceGap", { link = "Search" })
hi(0, "PounceMatch", { link = "Search" })
hi(0, "PreCondit", { fg = "#729fcf" })
hi(0, "PreProc", { link = "PreCondit" })
hi(0, "Question", { fg = "#44EAB0" })
hi(0, "RedrawDebugClear", { bg = "#44EAB0", fg = "#1c2026" })
hi(0, "RedrawDebugComposed", { bg = "#729fcf", fg = "#1c2026" })--ffb578"
hi(0, "RedrawDebugRecompose", { bg = "#fbadff", fg = "#1c2026" })
hi(0, "ReferencesCount", { fg = "#44EAB0" })
hi(0, "ReferencesIcon", { fg = "#44EAB0" })
hi(0, "Repeat", { fg = "#729fcf" })--ffb578"
hi(0, "SagaShadow", { bg = "#272f3a" })
hi(0, "Search", { bg = "#ABB4E3", fg = "#1c2026" })
hi(0, "SignAdd", { fg = "#fff3ca" })
hi(0, "SignChange", { fg = "#44EAB0" })
hi(0, "SignColumn", { fg = "#ABB4E3" })
hi(0, "SignDelete", { fg = "#fbadff" })
hi(0, "Special", { fg = "#fff3ca" })
hi(0, "SpecialComment", { fg = "#729fcf" })
hi(0, "SpecialKey", { fg = "#fff3ca" })
hi(0, "SpellBad", { sp = "#9a9184", undercurl = true })
hi(0, "SpellCap", { sp = "#9a9184", undercurl = true })
hi(0, "SpellLocal", { sp = "#9a9184", undercurl = true })
hi(0, "SpellRare", { sp = "#9a9184", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#729fcf" })--ffb578"
hi(0, "StatusLine", { fg = "#9a9184" })
hi(0, "StatusLineNC", { fg = "#737982" })
hi(0, "StatusLineTerm", { bg = "#729fcf", fg = "#1c2026" }) --ffb578"
hi(0, "StatusLineTermNC", { bg = "#a47957", blend = 60, fg = "#1c2026" })
hi(0, "StorageClass", { fg = "#fff3ca" })
hi(0, "String", { fg = "#494a47" })
hi(0, "Structure", { fg = "#fff3ca" })
hi(0, "Substitute", { link = "IncSearch" })
hi(0, "TabLine", { fg = "#9a9184" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bold = true, fg = "#ABB4E3" })
hi(0, "Tag", { fg = "#fff3ca" })
hi(0, "TargetWord", { fg = "#729fcf" })
hi(0, "TelescopeBorder", { fg = "#737982" })
hi(0, "TelescopeMatching", { fg = "#44EAB0" })
hi(0, "TelescopeNormal", { fg = "#9a9184" })
hi(0, "TelescopePromptNormal", { fg = "#ABB4E3" })
hi(0, "TelescopePromptPrefix", { fg = "#9a9184" })
hi(0, "TelescopeSelection", { bold = true, fg = "#ABB4E3" })
hi(0, "TelescopeSelectionCaret", { fg = "#44EAB0" })
hi(0, "TelescopeTitle", { bold = true, fg = "#fff3ca" })
hi(0, "Title", { bold = true, fg = "#fff3ca" })
hi(0, "Todo", { bg = "#164d44", blend = 20, fg = "#44EAB0" })
hi(0, "TreesitterContext", { bg = "#272f3a" })
hi(0, "TreesitterContextLineNumber", { bg = "#272f3a", fg = "#44EAB0" })
hi(0, "TroubleCount", { bg = "#222830", fg = "#729fcf" })
hi(0, "TroubleNormal", { bg = "#222830", fg = "#ABB4E3" })
hi(0, "TroubleText", { fg = "#9a9184" })
hi(0, "Type", { fg = "#fff3ca" })
hi(0, "Underlined", { fg = "#729fcf", underline = true })
hi(0, "VertSplit", { fg = "#737982" })
hi(0, "VimwikiHR", { fg = "#9a9184" })
hi(0, "VimwikiHeader1", { link = "markdownH1" })
hi(0, "VimwikiHeader2", { link = "markdownH2" })
hi(0, "VimwikiHeader3", { link = "markdownH3" })
hi(0, "VimwikiHeader4", { link = "markdownH4" })
hi(0, "VimwikiHeader5", { link = "markdownH5" })
hi(0, "VimwikiHeader6", { link = "markdownH6" })
hi(0, "VimwikiHeaderChar", { fg = "#9a9184" })
hi(0, "VimwikiLink", { link = "markdownUrl" })
hi(0, "VimwikiList", { fg = "#729fcf" })
hi(0, "VimwikiNoExistsLink", { fg = "#fbadff" })
hi(0, "Visual", { bg = "#4d535c" })
hi(0, "WarningMsg", { bold = true, fg = "#44EAB0" })
hi(0, "WhichKey", { fg = "#729fcf" })
hi(0, "WhichKeyDesc", { fg = "#44EAB0" })
hi(0, "WhichKeyGroup", { fg = "#fff3ca" })
hi(0, "WhichKeySeparator", { fg = "#9a9184" })
hi(0, "WhichKeyValue", { fg = "#44EAB0" })
hi(0, "WildMenu", { link = "IncSearch" })
hi(0, "WinBar", { bg = "#222830", fg = "#9a9184" })
hi(0, "WinBarNC", { bg = "#20252c", blend = 60, fg = "#737982" })
hi(0, "WinSeparator", { fg = "#737982" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "healthError", { fg = "#fbadff" })
hi(0, "healthSuccess", { fg = "#fff3ca" })
hi(0, "healthWarning", { fg = "#44EAB0" })
hi(0, "htmlArg", { fg = "#729fcf" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlEndTag", { fg = "#9a9184" })
hi(0, "htmlH1", { link = "markdownH1" })
hi(0, "htmlH2", { link = "markdownH2" })
hi(0, "htmlH3", { link = "markdownH3" })
hi(0, "htmlH4", { link = "markdownH4" })
hi(0, "htmlH5", { link = "markdownH5" })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlLink", { link = "markdownUrl" })
hi(0, "htmlTag", { fg = "#9a9184" })
hi(0, "htmlTagN", { fg = "#ABB4E3" })
hi(0, "htmlTagName", { fg = "#fff3ca" })
hi(0, "lCursor", { bg = "#ABB4E3" })
hi(0, "markdownDelimiter", { fg = "#9a9184" })
hi(0, "markdownH1", { bold = true, fg = "#729fcf" })
hi(0, "markdownH1Delimiter", { link = "markdownH1" })
hi(0, "markdownH2", { bold = true, fg = "#fff3ca" })
hi(0, "markdownH2Delimiter", { link = "markdownH2" })
hi(0, "markdownH3", { bold = true, fg = "#44EAB0" })
hi(0, "markdownH3Delimiter", { link = "markdownH3" })
hi(0, "markdownH4", { bold = true, fg = "#44EAB0" })
hi(0, "markdownH4Delimiter", { link = "markdownH4" })
hi(0, "markdownH5", { bold = true, fg = "#729fcf" }) --ffb578
hi(0, "markdownH5Delimiter", { link = "markdownH5" })
hi(0, "markdownH6", { bold = true, fg = "#fff3ca" })
hi(0, "markdownH6Delimiter", { link = "markdownH6" })
hi(0, "markdownLinkText", { link = "markdownUrl" })
hi(0, "markdownUrl", { fg = "#729fcf", sp = "#729fcf", underline = true })
hi(0, "mkdCode", { fg = "#fff3ca", italic = true })
hi(0, "mkdCodeDelimiter", { fg = "#44EAB0" })
hi(0, "mkdCodeEnd", { fg = "#fff3ca" })
hi(0, "mkdCodeStart", { fg = "#fff3ca" })
hi(0, "mkdFootnotes", { fg = "#fff3ca" })
hi(0, "mkdID", { fg = "#fff3ca", underline = true })
hi(0, "mkdInlineURL", { link = "markdownUrl" })
hi(0, "mkdLink", { link = "markdownUrl" })
hi(0, "mkdLinkDef", { link = "markdownUrl" })
hi(0, "mkdListItemLine", { fg = "#ABB4E3" })
hi(0, "mkdRule", { fg = "#9a9184" })
hi(0, "mkdURL", { link = "markdownUrl" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#272f3a"
g.terminal_color_1 = "#fbadff"
g.terminal_color_2 = "#729fcf"--ffb578"
g.terminal_color_3 = "#44EAB0"
g.terminal_color_4 = "#fff3ca"
g.terminal_color_5 = "#729fcf"
g.terminal_color_6 = "#44EAB0"
g.terminal_color_7 = "#ABB4E3"
g.terminal_color_8 = "#9a9184"
g.terminal_color_9 = "#fbadff"
g.terminal_color_10 = "#729fcf"--ffb578"
g.terminal_color_11 = "#44EAB0"
g.terminal_color_12 = "#fff3ca"
g.terminal_color_13 = "#729fcf"
g.terminal_color_14 = "#44EAB0"
g.terminal_color_15 = "#ABB4E3"
